export enum InvoiceStatus {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  CANCELED = 'CANCELED',
  LATE = 'LATE',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}
